FROM maven:sapmachine AS backend-builder

WORKDIR /usr/src/app/backend
COPY backend/ ./
RUN mvn clean package -DskipTests

FROM openjdk:21

WORKDIR /usr/src/app/backend
COPY --from=backend-builder /usr/src/app/backend/target/backend-0.0.1-SNAPSHOT.jar ./

EXPOSE 98

CMD ["java", "-jar", "backend-0.0.1-SNAPSHOT.jar"]
